### PR TITLE
Fix quoting for bash PS1 example

### PR DESCRIPTION
**Pull request by chriskepticode**

### CODE REVIEW

**Comment by jonmosco** [comment]
Changing to single quotes will also require removing the leading slash before kube_ps1:
`PS1='[\u@\h \W $(kube_ps1)]\$ '`

**Comment by chriskepticode** [comment]
Oh, yep -- updated.

**Comment by jonmosco** [comment]
If you dont mind squashing that commit, I will merge.

**Comment by chriskepticode** [comment]
Done, thanks.

**Pull request merged**
