### PR TITLE
Ability to display cluster name

### PR DESCRIPTION
**Pull request by ngealy**
I find it helpful to have the cluster name displayed, so I added that option in addition to the context and namespace.

### CODE REVIEW

**Comment by jonmosco** [comment]
Could you possibly squash this into one commit for review?

**Comment by ngealy** [comment]
Does that look better?

**Comment by mohideen** [comment]
This would be super useful when working with multiple clusters.

**Comment by jonmosco** [comment]
Question about this.  From gcloud docs, it states:
```
The current context is the cluster that is currently the default for kubectl:
all kubectl commands run against that cluster

When you create a cluster using gcloud container clusters create, an entry is automatically added to the kubeconfig file in your environment, and the current context changes to that cluster.
```

**Review by 19714 — APPROVED** [review]

**Comment by jonmosco** [comment]
Going to close this issue, thank you for the PR.  Trying to keep as little info in the prompt that can provide meaning without making it to long.

**Pull request closed without merging**
