### PR TITLE
fix zstat use -L option to follow symbol link wrongly

### PR DESCRIPTION
**Pull request by zyf0330**
fix https://github.com/ohmyzsh/ohmyzsh/issues/8786#issue-590928867

### CODE REVIEW

**Comment by mcornella** [comment]
As @zyf0330 said in the issue, `zstat`'s `-L` is the opposite of `stat -L`, see completion results:
```
$ zstat -[TAB]
-L  -- don't dereference symbolic links; use lstat(2)

$ stat -[TAB]
--dereference  -L  -- dereference symbolic links
```

**Comment by zyf0330** [comment]
@mcornella how does your doc promption of zstat work?

**Comment by mcornella** [comment]
You should get the completion entries when pressing TAB after `zstat -`.

**Comment by jonmosco** [comment]
Good find!  LGTM.

**Pull request merged**
