### PR TITLE
update readme to include arch linux aur repository

### PR DESCRIPTION
**Pull request by dijedodol**
I've added AUR Repository for Arch Linux users.

### CODE REVIEW

**Comment by jonmosco** [comment]
Oh nice, there is a package for this in arch?  How is it maintained?  Do you  have anymore information about it?

**Comment by grzesuav** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kube-ps1 -- seems like @dijedodol added it

**Comment by jonmosco** [comment]
Thanks for doing this, great to know its being packaged for Arch!

**Comment by dijedodol** [comment]
I'll try my best to update the aur package when new release is available here

**Pull request merged**
